app = 'better-booking-ollama'
primary_region = 'ord'

[build]
  image = 'ollama/ollama'

[[mounts]]
  source = 'models'
  destination = '/root/.ollama'
  initial_size = '100gb'

[http_service]
  internal_port = 11434
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpus = 16
  memory = "128gb"
  cpu_kind = "performance"
